ports:
    - port: 8000
    - port: 3000
tasks:
  - command: >
          pyenv gloval 3.7.4 &&
          pipenv install django 3.7.4 &&
          pipenv install djangoorestframework==3.10.3 &&
          pipenv install &&
          pipenv shell &&

          